spring.application.name=lecture2

# DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Hospital
spring.datasource.username=postgres
spring.datasource.password=@stric123

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries
spring.jpa.show-sql=true

# Format SQL nicely
spring.jpa.properties.hibernate.format_sql=true

#context path
server.servlet.context-path=/api





spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
